from __future__ import annotations

from gapsim.emulation.trench_depo import (
    DEFAULT_TRENCH_POINTS,
    ION_TRANSMISSION_STEPPED_TRENCH_POINTS,
    SWEEP_PARAMETER_LABELS,
    TrenchDepoConfig,
    TrenchDepoResult,
    TrenchSweepConfig,
    TrenchSweepResult,
    build_trench_depo_sweep_configs,
    compute_ion_transmission_factors,
    compute_reflected_ion_fields,
    direct_sputter_angle_response,
    direct_sputter_incident_angles_deg,
    run_trench_depo,
    run_trench_depo_legacy_sputter,
    run_trench_depo_sweep,
    vertex_air_normals,
)
from gapsim.emulation.model4_redeposition import (
    Model4RedepositionParams,
    Model4RedepositionResult,
    compute_arc_weights,
    compute_redeposition,
    line_of_sight,
)
from gapsim.emulation.trench_depo_export import (
    DEFAULT_RUNS_ROOT,
    export_trench_depo_run,
    load_trench_depo_run,
)
from gapsim.emulation.research_registry import (
    DEFAULT_CREATED_EMULATOR_NUMBERS,
    DEFAULT_RESEARCH_ROOT,
    EMULATOR_RESEARCH_SLOTS,
    EmulatorResearchSlot,
    emulator_research_paths,
    ensure_emulator_research_slot,
    ensure_emulator_research_tree,
    get_emulator_research_slot,
    iter_emulator_research_slots,
    load_created_emulator_numbers,
    next_emulator_number,
    save_created_emulator_numbers,
)

__all__ = [
    "DEFAULT_TRENCH_POINTS",
    "ION_TRANSMISSION_STEPPED_TRENCH_POINTS",
    "DEFAULT_RESEARCH_ROOT",
    "DEFAULT_CREATED_EMULATOR_NUMBERS",
    "DEFAULT_RUNS_ROOT",
    "EMULATOR_RESEARCH_SLOTS",
    "EmulatorResearchSlot",
    "Model4RedepositionParams",
    "Model4RedepositionResult",
    "SWEEP_PARAMETER_LABELS",
    "TrenchDepoConfig",
    "TrenchDepoResult",
    "TrenchSweepConfig",
    "TrenchSweepResult",
    "build_trench_depo_sweep_configs",
    "compute_arc_weights",
    "compute_ion_transmission_factors",
    "compute_redeposition",
    "compute_reflected_ion_fields",
    "direct_sputter_angle_response",
    "direct_sputter_incident_angles_deg",
    "emulator_research_paths",
    "ensure_emulator_research_slot",
    "ensure_emulator_research_tree",
    "export_trench_depo_run",
    "get_emulator_research_slot",
    "iter_emulator_research_slots",
    "load_trench_depo_run",
    "load_created_emulator_numbers",
    "line_of_sight",
    "next_emulator_number",
    "save_created_emulator_numbers",
    "run_trench_depo",
    "run_trench_depo_legacy_sputter",
    "run_trench_depo_sweep",
    "vertex_air_normals",
]
